# Generated by Django 5.0.7 on 2024-08-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_homenews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeNews',
        ),
        migrations.DeleteModel(
            name='SinglNews',
        ),
    ]
